language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t codistro/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true codistro/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-747473571860"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
